### PR TITLE
Bug found and fixed in ezstream.c

### PR DESCRIPTION
**Pull request by tommccallum**
Hi,

I found a bug where if no decoders or encoders exist then it led to a seg fault in _build_reencode_cmd, in ezstream.c.  The issue was that when one of these strings was NULL the strstr expression around custom_songinfo segfaulted.  

Hope this helps,

Tom

It can be reproduced with the following config file:

<ezstream>
	<servers>
		<server>
			<hostname>your_hostname</hostname>
			<password>your_password</password>
		</server>
	</servers>
	<streams>
		<stream>
			<mountpoint>/stream</mountpoint>
			<format>MP3</format>
			<intake>Test Input</intake>
			<public>No</public>
			<encoder>passthrough</encoder>
		</stream>
	</streams>

	<intakes>
		<intake>
			<name>Test Input</name>
			<type>program</type>
			<filename>your_script</filename>
			<shuffle>No</shuffle>
			<stream_once>Yes</stream_once>
		</intake>
	</intakes>

    <decoders>
        <decoder>
        <name>m4a</name>
        
        <program>ffmpeg -i @T@ -f wav -</program>
        <file_ext>.m4a</file_ext>
        </decoder>
    </decoders>

    <encoders>
        <encoder>
            <name>passthrough</name>
            <format>Theora</format>
        </encoder>
    </encoders>
	
</ezstream>

### CODE REVIEW

**Comment by mgrimm** [comment]
Hi Tom,

Please note that this repository is just a mirror. The master is here: https://gitlab.xiph.org/xiph/ezstream and the synchronization is currently broken (you are not working on the latest HEAD).
I hope to find some time soon to look at the segfault you found.
I'm confused about your PR here and it's not obvious what you're trying to do (yet). If you want stuff merged, please make sure to maintain or improve unit test coverage by writing meaningful tests for your changes, and keep it tidy (don't add whitespace at EOL, etc.) If you add a feature, don't forget the documentation and configuration examples. Thanks!

Best regards,
-Moritz

**Comment by tommccallum** [comment]
Thanks Moritz, appreciate your feedback.

**Comment by mgrimm** [comment]
Your discovery of that segfault prompted me to go clean up some more. It uncovered that "pass through" was actually implemented twice. I have removed the "pass through encoder" variant, which is what I originally intended and already documented up front. Please see the upstream HEAD in Xiph.org's GitLab for reference.
I'm closing the PR here now, especially since it contains other unrelated changes.
Thanks for the report!

**Comment by tommccallum** [comment]
That's good news, glad I could help.  This was my first attempt at a push
request for an open source project and appreciate your feedback earlier.

**Pull request closed without merging**
